"""
Django settings for {{project_name}} project.

Generated by 'django-admin startproject' using Django 4.2.11.

For more information on this file, see
https://docs.djangoproject.com/en/4.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.2/ref/settings/
"""

import os
from pathlib                    import Path
from django.templatetags.static import static
from django.urls                import reverse_lazy
from django.utils.translation   import gettext_lazy as _
from dotenv                     import load_dotenv
load_dotenv()

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.getenv('SECRET_KEY')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.getenv('DEBUG', 'True').lower() in ('true', '1', 'yes')
print(f"DEBUG mode is set to: {DEBUG}")

ALLOWED_HOSTS = ['*']


# Application definition

INSTALLED_APPS = [
    'unfold',  # before django.contrib.admin
    'unfold.contrib.filters',  # optional, if special filters are needed
    'unfold.contrib.forms',  # optional, if special form elements are needed
    'unfold.contrib.import_export',  # optional, if django-import-export package is used
    'unfold.contrib.guardian',  # optional, if django-guardian package is used
    'unfold.contrib.simple_history',  # optional, if django-simple-history package is used

    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',

    'django_cleanup.apps.CleanupConfig',
    'tinymce',
    'import_export',
    'corsheaders',

    'django_filters', # Django Filters
    'rest_framework', # Django Rest Framework
    'django_api_helper', # Django API Admin

    'api',
]

APPEND_SLASH                = True

MIDDLEWARE = [
    'corsheaders.middleware.CorsMiddleware',  # This should be near the top
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = '{{project_name}}.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR, 'templates')],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = '{{project_name}}.wsgi.application'


# Database
# https://docs.djangoproject.com/en/4.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/4.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/4.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'Asia/Kolkata'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.2/howto/static-files/

STATIC_URL = '/static/'
STATIC_ROOT =  os.path.join(BASE_DIR, 'static')
MEDIA_URL = '/media/'
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')

# Default primary key field type
# https://docs.djangoproject.com/en/4.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'


# Django Rest Framework
REST_FRAMEWORK = {
    'DEFAULT_RENDERER_CLASSES': [
        'rest_framework.renderers.BrowsableAPIRenderer',
        'rest_framework.renderers.JSONRenderer',
    ], 
    'DEFAULT_PAGINATION_CLASS': 'django_api_helper.pagination.CustomPageNumberPagination',
    'DEFAULT_FILTER_BACKENDS': ['django_filters.rest_framework.DjangoFilterBackend'],
    'PAGE_SIZE': 24,  # Number of results per page
}
SERIALIZER_MIN_DEPTH = 1
SERIALIZER_MAX_DEPTH = 3

if DEBUG:
    CSRF_TRUSTED_ORIGINS = [
        "https://*.scotttiger.in",
        "http://*.scotttiger.in",
        "http://localhost:3000",
        "http://127.0.0.1:3000", 
        "http://localhost:8000",
        "http://127.0.0.1:8000",    
    ]
    CSRF_COOKIE_SECURE = False
    CORS_ALLOW_HEADERS = ['*']
    CORS_ALLOW_METHODS = ['*']
    CORS_ALLOW_CREDENTIALS = True
    CORS_ORIGIN_ALLOW_ALL = True

else:
    # CORS
    CORS_ALLOW_METHODS = [
        'GET',
        'POST',
        'PUT',
        'PATCH',
        'DELETE',
        'OPTIONS'
    ]
    # CORS_ALLOW_ALL_ORIGINS = True
    CORS_ALLOWED_ORIGINS = [
        "http://localhost:3000",  # Add your frontend's URL here
        "http://localhost:8000",  # Add your frontend's URL here
        "https://{{project_name}}.vercel.app",
        "http://{{project_name}}.com",
        "https://{{project_name}}.com",
        "http://api.{{project_name}}.com",
        "https://api.{{project_name}}.com",
        "http://www.{{project_name}}.com",
        "https://www.{{project_name}}.com",
    ]
    CSRF_TRUSTED_ORIGINS = [
        "http://localhost:3000",  # Add your frontend's URL here
        "http://localhost:8000",  # Add your frontend's URL here
        "https://{{project_name}}.vercel.app",
        "http://{{project_name}}.com",
        "https://{{project_name}}.com",
        "http://api.{{project_name}}.com",
        "https://api.{{project_name}}.com",
        "http://www.{{project_name}}.com",
        "https://www.{{project_name}}.com",
    ]
    CORS_ALLOW_CREDENTIALS = True # If you need to allow credentials (cookies) in your request
    CORS_ALLOW_HEADERS = ['*']


EMAIL_BACKEND       = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_HOST          = os.getenv('EMAIL_HOST_USER')
EMAIL_PORT          = 587
EMAIL_USE_TLS       = True
EMAIL_HOST_USER     = os.getenv('EMAIL_HOST_USER')
EMAIL_HOST_PASSWORD = os.getenv('EMAIL_HOST_PASSWORD')
DEFAULT_FROM_EMAIL  = EMAIL_HOST_USER

UNFOLD = {
    "SITE_TITLE": f"{'{{project_name}}'.replace('_', ' ').title()} Admin",
    "SITE_HEADER": f"{'{{project_name}}'.replace('_', ' ').title()}",
    "SITE_SUBHEADER": f"{'{{project_name}}'.replace('_', ' ').title()} Administration",
    "SITE_URL": "https://{{project_name}}.com/",
    "SITE_SYMBOL": "dashboard",
    "SHOW_VIEW_ON_SITE": True,
    # "THEME": "light",

    "SIDEBAR": {
        "navigation": [
            # Dashboard / Main
            {
                "title": _("Main Navigation"),
                "separator": True,
                "items": [
                    {
                        "title": _("Dashboard"),
                        "icon": "dashboard",
                        "link": reverse_lazy("admin:index"),
                        "permission": lambda request: request.user.is_superuser,
                    },
                ],
            },

            # Settings
            {
                "title": _("Global Settings"),
                "icon": "settings",
                "separator": True,
                "items": [
                    {
                        "title": _("Site Settings"),
                        "icon": "settings_applications",
                        "link": reverse_lazy("admin:api_sitesetting_changelist"),
                    },
                ],
            },

            # Media
            {
                "title": _("Media"),
                "icon": "perm_media",
                "separator": True,
                "items": [
                    {
                        "title": _("Image Master"),
                        "icon": "image",
                        "link": reverse_lazy("admin:api_imagemaster_changelist"),
                    },
                    {
                        "title": _("File Master"),
                        "icon": "folder",
                        "link": reverse_lazy("admin:api_filemaster_changelist"),
                    },
                    {
                        "title": _("Banner Image"),
                        "icon": "image",
                        "link": reverse_lazy("admin:api_bannerimage_changelist"),
                    }
                ],
            },

            # Contacts & Core
            {
                "title": _("Contacts & Core"),
                "icon": "contact_mail",
                "separator": True,
                "items": [
                    {
                        "title": _("Contacts"),
                        "icon": "contact_page",
                        "link": reverse_lazy("admin:api_contact_changelist"),
                    },
                ],
            },

            # Blog
            {
                "title": _("Blog"),
                "icon": "article",
                "separator": True,
                "items": [
                    {
                        "title": _("Blog Categories"),
                        "icon": "category",
                        "link": reverse_lazy("admin:api_blogcategory_changelist"),
                    },
                    {
                        "title": _("Blogs"),
                        "icon": "article",
                        "link": reverse_lazy("admin:api_blog_changelist"),
                    },
                ],
            },

            # FAQs
            {
                "title": _("FAQs"),
                "icon": "help",
                "separator": True,
                "items": [
                    {
                        "title": _("FAQ Categories"),
                        "icon": "category",
                        "link": reverse_lazy("admin:api_faqcategory_changelist"),
                    },
                    {
                        "title": _("FAQs"),
                        "icon": "help_outline",
                        "link": reverse_lazy("admin:api_faq_changelist"),
                    },
                ],
            },

            # Testimonials
            {
                "title": _("Testimonials"),
                "icon": "format_quote",
                "separator": True,
                "items": [
                    {
                        "title": _("Testimonials"),
                        "icon": "format_quote",
                        "link": reverse_lazy("admin:api_testimonial_changelist"),
                    },
                ],
            },
            # Testimonials
            {
                "title": _("SEO"),
                "icon": "format_quote",
                "separator": True,
                "items": [
                    {
                        "title": _("Dynamic Head"),
                        "icon": "format_quote",
                        "link": reverse_lazy("admin:api_head_changelist"),
                    },
                ],
            },
        ],
    },
}