"""
Django settings for {{project_name}} project.

Generated by 'django-admin startproject' using Django 4.2.11.

For more information on this file, see
https://docs.djangoproject.com/en/4.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.2/ref/settings/
"""

import os
from pathlib                    import Path
from datetime                   import timedelta
from django.templatetags.static import static
from django.urls                import reverse_lazy
from django.utils.translation   import gettext_lazy as _
from corsheaders.defaults       import default_headers
from dotenv                     import load_dotenv


from .logging_config           import LOGGING
from .loggers                  import django_console_logger


load_dotenv()

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


def env_list(name, default=""):
    """Read a comma-separated environment variable into a clean list."""
    return [item.strip() for item in os.getenv(name, default).split(",") if item.strip()]


def env_bool(name, default="False"):
    return os.getenv(name, default).strip().lower() in ("true", "1", "yes", "on")


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY  = os.getenv("SECRET_KEY")
DEBUG       = env_bool("DEBUG", "True")

if DEBUG:
    django_console_logger.warning("Using in DEBUG mode")
else:
    django_console_logger.info("Using in PRODUCTION mode")

if not SECRET_KEY:
    # Fail loudly rather than starting with an empty key.
    raise RuntimeError("SECRET_KEY is not set. Add it to .env before starting the project.")


# Permissive in development so the test client, ngrok, and LAN access all work.
# Production reads the explicit list from .env.
if DEBUG:
    ALLOWED_HOSTS = ["*"]
else:
    ALLOWED_HOSTS = env_list("ALLOWED_HOSTS", "localhost,127.0.0.1")

# Public base URL of the frontend that consumes this API.
# Used to build password reset links, so it must point at the app, not the API.
FRONTEND_URL = os.getenv("FRONTEND_URL", "http://localhost:3000").rstrip("/")


# Application definition

INSTALLED_APPS = [
    'unfold',  # before django.contrib.admin
    'unfold.contrib.filters',  # optional, if special filters are needed
    'unfold.contrib.forms',  # optional, if special form elements are needed
    'unfold.contrib.import_export',  # optional, if django-import-export package is used
    'unfold.contrib.guardian',  # optional, if django-guardian package is used
    'unfold.contrib.simple_history',  # optional, if django-simple-history package is used

    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',

    'django_cleanup.apps.CleanupConfig',
    'tinymce',
    'import_export',
    'corsheaders',

    'django_filters', # Django Filters
    'rest_framework',
    'rest_framework_simplejwt',
    'rest_framework_simplejwt.token_blacklist',
    'django_api_helper',

    'api',
]


AUTH_USER_MODEL = 'api.User'

APPEND_SLASH                = True

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'corsheaders.middleware.CorsMiddleware',  # This should be near the top
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = '{{project_name}}.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR, 'templates')],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = '{{project_name}}.wsgi.application'


# Database
# https://docs.djangoproject.com/en/4.2/ref/settings/#databases

# SQLite by default so a fresh checkout runs with no services.
# Set DB_NAME in .env to switch to PostgreSQL.
if os.getenv("DB_NAME"):
    DATABASES = {
        'default': {
            'ENGINE'    : 'django.db.backends.postgresql',
            'NAME'      : os.getenv("DB_NAME"),
            'USER'      : os.getenv("DB_USER", "postgres"),
            'PASSWORD'  : os.getenv("DB_PASSWORD", ""),
            'HOST'      : os.getenv("DB_HOST", "127.0.0.1"),
            'PORT'      : os.getenv("DB_PORT", "5432"),
            'CONN_MAX_AGE': int(os.getenv("DB_CONN_MAX_AGE", "60")),
        }
    }
else:
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.sqlite3',
            'NAME': BASE_DIR / 'db.sqlite3',
        }
    }


# Password validation
# https://docs.djangoproject.com/en/4.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/4.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'Asia/Kolkata'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.2/howto/static-files/

STATIC_URL = '/static/'
STATIC_ROOT =  os.path.join(BASE_DIR, 'static')
MEDIA_URL = '/media/'
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')

# Default primary key field type
# https://docs.djangoproject.com/en/4.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'


# Django Rest Framework
REST_FRAMEWORK = {
    'DEFAULT_RENDERER_CLASSES': [
        'rest_framework.renderers.JSONRenderer',
    ], 
    'DEFAULT_PAGINATION_CLASS': 'django_api_helper.pagination.CustomPageNumberPagination',
    'DEFAULT_FILTER_BACKENDS': ['django_filters.rest_framework.DjangoFilterBackend'],
    'PAGE_SIZE': 20,  # Number of results per page
    'DEFAULT_AUTHENTICATION_CLASSES': [
        'rest_framework_simplejwt.authentication.JWTAuthentication',
        'rest_framework.authentication.SessionAuthentication',
    ],
}
SERIALIZER_MIN_DEPTH = 1
SERIALIZER_MAX_DEPTH = 3

SIMPLE_JWT = {
    'ACCESS_TOKEN_LIFETIME': timedelta(minutes=30),
    'REFRESH_TOKEN_LIFETIME': timedelta(days=15),
    'ROTATE_REFRESH_TOKENS': False,
    'BLACKLIST_AFTER_ROTATION': True,
    'UPDATE_LAST_LOGIN': True,
}

# Changed
CORS_ALLOW_CREDENTIALS = True

CORS_ALLOW_HEADERS = list(default_headers) + [
    "ngrok-skip-browser-warning",
]

CORS_ALLOW_METHODS = [
    "GET",
    "POST",
    "PUT",
    "PATCH",
    "DELETE",
    "OPTIONS",
]

# Production origins come from .env so a deploy never needs a code change.
# Format: CORS_ALLOWED_ORIGINS=https://example.com,https://www.example.com
COMMON_ORIGINS = env_list("CORS_ALLOWED_ORIGINS")

LOCAL_ORIGINS = [
    "http://localhost:3000",
    "http://127.0.0.1:3000",
    "http://localhost:8000",
    "http://127.0.0.1:8000",
]

if DEBUG:
    # Changed
    CORS_ALLOW_ALL_ORIGINS = True

    CSRF_TRUSTED_ORIGINS = [
        *COMMON_ORIGINS,
        *LOCAL_ORIGINS,
        "https://*.ngrok-free.app",
    ]

    CSRF_COOKIE_SECURE = False
    SESSION_COOKIE_SECURE = False
    REST_FRAMEWORK['DEFAULT_RENDERER_CLASSES'].append(
        'rest_framework.renderers.BrowsableAPIRenderer'
    )
else:
    # Changed
    CORS_ALLOWED_ORIGINS = [
        *COMMON_ORIGINS,
    ]

    CSRF_TRUSTED_ORIGINS = [
        *COMMON_ORIGINS,
    ]

    CSRF_COOKIE_SECURE = True
    SESSION_COOKIE_SECURE = True

    # Optional but recommended for production
    SECURE_SSL_REDIRECT = True
    SECURE_HSTS_SECONDS = 31536000
    SECURE_HSTS_INCLUDE_SUBDOMAINS = True
    SECURE_HSTS_PRELOAD = True
    SECURE_CONTENT_TYPE_NOSNIFF = True
    SECURE_BROWSER_XSS_FILTER = True


EMAIL_BACKEND       = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_HOST          = os.getenv('EMAIL_HOST_USER')
EMAIL_PORT          = 587
EMAIL_USE_TLS       = True
EMAIL_HOST_USER     = os.getenv('EMAIL_HOST_USER')
EMAIL_HOST_PASSWORD = os.getenv('EMAIL_HOST_PASSWORD')
DEFAULT_FROM_EMAIL  = EMAIL_HOST_USER

# Redis is optional for local work. Set REDIS_URL in .env to switch the cache
# over; without it the project runs on an in-process cache so a fresh checkout
# starts with no external services.
REDIS_URL = os.getenv("REDIS_URL", "").strip()

if REDIS_URL:
    CACHES = {
        "default": {
            "BACKEND": "django_redis.cache.RedisCache",
            "LOCATION": REDIS_URL,
            "OPTIONS": {"CLIENT_CLASS": "django_redis.client.DefaultClient"},
        }
    }
else:
    CACHES = {
        "default": {
            "BACKEND": "django.core.cache.backends.locmem.LocMemCache",
            "LOCATION": "{{project_name}}-locmem",
        }
    }
    if not DEBUG:
        django_console_logger.warning("REDIS_URL is not set; falling back to a per-process cache.")

UNFOLD = {
    "SITE_TITLE": f"{'{{project_name}}'.replace('_', ' ').title()} Admin",
    "SITE_HEADER": f"{'{{project_name}}'.replace('_', ' ').title()}",
    "SITE_SUBHEADER": f"{'{{project_name}}'.replace('_', ' ').title()} Administration",
    "SITE_URL": FRONTEND_URL,
    "SITE_SYMBOL": "dashboard",
    "SHOW_VIEW_ON_SITE": True,
    # "THEME": "light",

    "SIDEBAR": {
        "navigation": [
            # Dashboard / Main
            {
                "title": _("Main Navigation"),
                "separator": True,
                "items": [
                    {
                        "title": _("Dashboard"),
                        "icon": "dashboard",
                        "link": reverse_lazy("admin:index"),
                        "permission": lambda request: request.user.is_superuser,
                    },
                ],
            },

            # Settings
            {
                "title": _("Global Settings"),
                "icon": "settings",
                "separator": True,
                "items": [
                    {
                        "title": _("Site Settings"),
                        "icon": "settings_applications",
                        "link": reverse_lazy("admin:api_sitesetting_changelist"),
                    },
                ],
            },

            # Media
            {
                "title": _("Media"),
                "icon": "perm_media",
                "separator": True,
                "items": [
                    {
                        "title": _("Image Master"),
                        "icon": "image",
                        "link": reverse_lazy("admin:api_imagemaster_changelist"),
                    },
                    {
                        "title": _("File Master"),
                        "icon": "folder",
                        "link": reverse_lazy("admin:api_filemaster_changelist"),
                    },
                    {
                        "title": _("Banner Image"),
                        "icon": "image",
                        "link": reverse_lazy("admin:api_bannerimage_changelist"),
                    }
                ],
            },

            # Contacts & Core
            {
                "title": _("Contacts & Core"),
                "icon": "contact_mail",
                "separator": True,
                "items": [
                    {
                        "title": _("Contacts"),
                        "icon": "contact_page",
                        "link": reverse_lazy("admin:api_contact_changelist"),
                    },
                ],
            },

            # Blog
            {
                "title": _("Blog"),
                "icon": "article",
                "separator": True,
                "items": [
                    {
                        "title": _("Blog Categories"),
                        "icon": "category",
                        "link": reverse_lazy("admin:api_blogcategory_changelist"),
                    },
                    {
                        "title": _("Blogs"),
                        "icon": "article",
                        "link": reverse_lazy("admin:api_blog_changelist"),
                    },
                ],
            },

            # FAQs
            {
                "title": _("FAQs"),
                "icon": "help",
                "separator": True,
                "items": [
                    {
                        "title": _("FAQ Categories"),
                        "icon": "category",
                        "link": reverse_lazy("admin:api_faqcategory_changelist"),
                    },
                    {
                        "title": _("FAQs"),
                        "icon": "help_outline",
                        "link": reverse_lazy("admin:api_faq_changelist"),
                    },
                ],
            },

            # Testimonials
            {
                "title": _("Testimonials"),
                "icon": "format_quote",
                "separator": True,
                "items": [
                    {
                        "title": _("Testimonials"),
                        "icon": "format_quote",
                        "link": reverse_lazy("admin:api_testimonial_changelist"),
                    },
                ],
            },
            # Testimonials
            {
                "title": _("SEO"),
                "icon": "format_quote",
                "separator": True,
                "items": [
                    {
                        "title": _("Dynamic Head"),
                        "icon": "format_quote",
                        "link": reverse_lazy("admin:api_head_changelist"),
                    },
                ],
            },
        ],
    },
}